[project]
name = "estudando-kafka"
version = "1.0"
requires-python = ">=3.14"
dependencies = ["fastapi[standard]", "argon2-cffi", "loguru"]

[project.optional-dependencies]
dev = [
    "black",
    "ipdb",
    "isort",
    "pylint",
    "pytest",
    "pytest-cov",
    "pytest-sugar",
]


[tool.black]
line-length = 79
target-version = ['py314']
include = '\.pyi?$'

[tool.pytest.ini_options]
addopts = "-v -sx"
pythonpath = "."
